version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: kokorink/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: kokorink/foodgram_frontend
    volumes:
      - static:/app/build/
    depends_on:
      - backend
  gateway:
    image: kokorink/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/staticfiles
      - media:/mediafiles
    depends_on:
      - frontend
